### ISSUE TITLE
Warn "Error: Meteor data 'subscribe' ( in v2.0.0-beta3 )

### ISSUE THREAD

**Issue by mathieustan** [meteor-vue/vue-meteor-tracker#28]
Hello, 

We just tried last version of meteor-vue-tracker (beta3).
A package seems to add a subscribe property into meteor statement but we dont know which one. 
We are using vue-supply, meteor-vue-tracker and vuex together.  

Of couse, we inspected all files, we couldn't find any subscribe property anywhere ... 

### supply.js
<img width="520" alt="capture d ecran 2018-05-21 a 15 28 06" src="https://user-images.githubusercontent.com/38033090/40309974-a65185a8-5d0b-11e8-8c94-6e63d6417405.png">

### console.log from supply/base.js:
<img width="223" alt="capture d ecran 2018-05-21 a 15 15 03" src="https://user-images.githubusercontent.com/38033090/40309873-59577e92-5d0b-11e8-8b4c-c759d37d031f.png">

### Error : 
<img width="409" alt="capture d ecran 2018-05-21 a 15 26 44" src="https://user-images.githubusercontent.com/38033090/40309890-6bf78bd2-5d0b-11e8-9137-47878dd541e2.png">

Do you have any idea ? 

 **EDIT: it works with beta 2.0.0-beta.1**

**Comment by mathieustan** [comment]
Solution: 
https://github.com/meteor-vue/vue-meteor-tracker/blob/master/src/index.js#L96

change with: `if (key.charAt(0) !== '$' && key !== 'subscribe')`

**Comment by Billybobbonnet** [comment]
@mathieustan Thanks for opening that issue. I finally decided to switch from baze to vue and struggled to find what it came from all day.

It turns out I found it was about the version and minutes after that I found this issue.

For the record, I took [the example](https://github.com/Akryum/meteor-vue2-example) as reference and it is then broken with the latest versions, if the dev updates the node packages.

@Akryum Are PR welcome based on @mathieustan fix?
