### ISSUE TITLE
Warn:  Cannot read property 'push' of null ( in v2.0.0-beta3 )

### ISSUE THREAD

**Issue by mathieustan** [meteor-vue/vue-meteor-tracker#29]
**1st Issue:**
------
When I enter in a vue component using a registered vue-supply (with subscribes) , I get that error: 
`Cannot read property 'push' of null`

This error comes from this line : 
https://github.com/meteor-vue/vue-meteor-tracker/blob/6f6a1433b2037194aaed68ac51288138335d8784/src/index.js#L136

this._trackerHandles is equal to null, and I couldn't find any reason.
in $stopMeteor method, this._trackerHandles is set to null, but it didn't get called.

Maybe we could do something like : `if (!this._trackerHandles) this._trackerHandles = [];`

**2nd issue:**
------
Vue component seems to have a cache. 

1/ I load for the first time a component, everything works fine. 
2/ Then, I leave this component by going to another route (so component is destroyed)
3/ Finaly, I come back into my inital component (changing route again)

`Meteor data '${key}': Property already used in the component data, props or other`

This error comes from this line: 
https://github.com/meteor-vue/vue-meteor-tracker/blob/6f6a1433b2037194aaed68ac51288138335d8784/src/index.js#L229

and more specificly from this statement : `hasProperty(this, key)`

My vue component already know `key` property

I think we should only check for `(hasProperty(this.$data, key) || hasProperty(this.$props, key)`

**Comment by jan-san** [comment]
Regarding the 1st issue (`Cannot read property 'push' of null` for `_trackerHandles`), in my case this exception was caused by a call to `$subscribe` after the component was destroyed (a result of wrapping the call in `lodash.unbounce()`).

So it wasn't an issue in `vue-meteor-tracker`, but it would make sense to catch this case and throw a more meaningful exception.

In case somebody else runs into this issue, it can be fixed by cancelling the debounced method in the component's [`beforeDestroy` hook](https://vuejs.org/v2/api/#beforeDestroy):
```js
beforeDestroy() {
  // cancel debounced methods to prevent calling them after the component was destroyed
  this.debouncedMethod.cancel();
},
```
